name: 'PermissionAPI'
version: '1.0.0'
api-version: '1.20'
main: 'net.opsucht.permissionapi.PermissionAPIPlugin'
softdepend:
  - 'LuckPerms'
  - 'GroupManager'
  - 'PermissionsEx'
commands:
  test:
    description: "Test command for testing features"
    usage: "/test"